name: Deploy to AWS

on:
  push:
    branches:
      - main  # Se activa cada vez que hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Zafiro_infraestructura  # Cambia esto por la ruta real en tu AWS
            git pull origin main
            sudo docker compose up -d --build